In [22]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,PatientID,Age,AgeGroup,AlcoholConsumption,BMI,Bradykinesia,CholesterolHDL,CholesterolLDL,CholesterolTotal,CholesterolTriglycerides,...,SleepDisorders,SleepQuality,Smoking,SpeechProblems,Stroke,SystolicBP,TraumaticBrainInjury,Tremor,UPDRS,Diagnosis
0,d4e0fb07-37c6-4c7d-a9d5-bfadc41b8164,56,1,14.401750,38.165782,False,98.305359,185.601755,214.446455,177.613258,...,False,8.839484,0,True,0,173,0,False,114.941744,0
1,97cb29cd-aa0c-4802-80ee-4fb82c0d5059,84,3,15.545237,33.877785,False,29.089431,130.446298,168.545178,237.987107,...,False,6.183109,0,False,0,111,0,True,191.992824,1
2,d9584f0e-f6fb-4821-8737-679a25f4c5cd,53,1,5.942235,30.111818,False,40.764986,186.558645,291.316103,342.071323,...,False,8.590509,0,False,0,161,0,False,121.425375,0
3,d3cb6b85-7286-4b09-9f6f-349ad8e34bd1,88,3,7.315375,19.931085,False,38.752199,191.811289,174.858648,375.127417,...,False,6.359914,0,False,0,122,1,False,30.952378,0
4,d6b091f4-099a-4f85-8417-2cb7110e4f93,77,3,6.037814,32.591481,True,32.477083,118.043431,231.507811,385.517466,...,False,4.679000,0,False,0,113,0,True,63.069273,1

In [23]:
#subtasks

def get_cardio_risk(row):
    score = (row.Hypertension == 1) + (row.Diabetes == 1) + (row.BMI > 30)
    return score

def get_life_risk(row):
    score = (row.Smoking == 1) + (row.AlcoholConsumption > 2) + (row.PhysicalActivity < 1)
    return score

subtask1 = df_test.apply(get_cardio_risk, axis=1)
subtask2 = df_test.apply(get_life_risk, axis=1)

df_1 = pd.DataFrame({
    "PatientID": df_test.PatientID,
    "subtaskID": "Task1",
    "Answer": subtask1
})

df_2 = pd.DataFrame({
    "PatientID": df_test.PatientID,
    "subtaskID": "Task2",
    "Answer": subtask2
})

subtasks = pd.concat([df_1, df_2])
subtasks

                                PatientID subtaskID  Answer
0    a00fa494-651e-4674-8fb8-aa006b14cbf7     Task1       0
1    f31cda69-4e3f-4265-928c-3fe9b83f0896     Task1       1
2    e4d181d2-803a-42f5-8065-239dd591fb9d     Task1       0
3    c585efb2-37e3-4620-aeda-a2299191d3a9     Task1       2
4    74fbfa2b-901e-4028-b325-9aaaa07cbf4d     Task1       0
..                                    ...       ...     ...
416  3fd9395f-eb15-4462-b022-d449e9e1d2d4     Task2       1
417  c2221f9b-fcc0-48c2-a988-90eb10a9857b     Task2       1
418  8818b962-4645-42f6-88c7-9a1f26fae3d8     Task2       2
419  4b46f134-1962-444e-ab2e-f35e24fca2b7     Task2       1
420  f16fc91c-ec4c-4440-b316-48d4e9084dc1     Task2       1

[842 rows x 3 columns]

In [24]:
#preprocessing

df_train = df_train.drop(columns = ['DoctorInCharge', 'EyeColor'])
df_test = df_test.drop(columns = ['DoctorInCharge', 'EyeColor'])

df_train.head()

,PatientID,Age,AgeGroup,AlcoholConsumption,BMI,Bradykinesia,CholesterolHDL,CholesterolLDL,CholesterolTotal,CholesterolTriglycerides,...,SleepDisorders,SleepQuality,Smoking,SpeechProblems,Stroke,SystolicBP,TraumaticBrainInjury,Tremor,UPDRS,Diagnosis
0,d4e0fb07-37c6-4c7d-a9d5-bfadc41b8164,56,1,14.401750,38.165782,False,98.305359,185.601755,214.446455,177.613258,...,False,8.839484,0,True,0,173,0,False,114.941744,0
1,97cb29cd-aa0c-4802-80ee-4fb82c0d5059,84,3,15.545237,33.877785,False,29.089431,130.446298,168.545178,237.987107,...,False,6.183109,0,False,0,111,0,True,191.992824,1
2,d9584f0e-f6fb-4821-8737-679a25f4c5cd,53,1,5.942235,30.111818,False,40.764986,186.558645,291.316103,342.071323,...,False,8.590509,0,False,0,161,0,False,121.425375,0
3,d3cb6b85-7286-4b09-9f6f-349ad8e34bd1,88,3,7.315375,19.931085,False,38.752199,191.811289,174.858648,375.127417,...,False,6.359914,0,False,0,122,1,False,30.952378,0
4,d6b091f4-099a-4f85-8417-2cb7110e4f93,77,3,6.037814,32.591481,True,32.477083,118.043431,231.507811,385.517466,...,False,4.679000,0,False,0,113,0,True,63.069273,1

In [27]:
features = [col for col in df_test.columns if col != 'PatientID']
target = 'Diagnosis'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

X.head()

,Age,AgeGroup,AlcoholConsumption,BMI,Bradykinesia,CholesterolHDL,CholesterolLDL,CholesterolTotal,CholesterolTriglycerides,Constipation,...,Rigidity,SleepDisorders,SleepQuality,Smoking,SpeechProblems,Stroke,SystolicBP,TraumaticBrainInjury,Tremor,UPDRS
0,56,1,14.401750,38.165782,False,98.305359,185.601755,214.446455,177.613258,True,...,False,False,8.839484,0,True,0,173,0,False,114.941744
1,84,3,15.545237,33.877785,False,29.089431,130.446298,168.545178,237.987107,False,...,False,False,6.183109,0,False,0,111,0,True,191.992824
2,53,1,5.942235,30.111818,False,40.764986,186.558645,291.316103,342.071323,False,...,False,False,8.590509,0,False,0,161,0,False,121.425375
3,88,3,7.315375,19.931085,False,38.752199,191.811289,174.858648,375.127417,False,...,True,False,6.359914,0,False,0,122,1,False,30.952378
4,77,3,6.037814,32.591481,True,32.477083,118.043431,231.507811,385.517466,False,...,True,False,4.679000,0,False,0,113,0,True,63.069273

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score

model = RandomForestClassifier(random_state=42)

cross_val_score(model, X, y, cv=5, scoring='roc_auc')

array([0.95617174, 0.96271307, 0.93733179, 0.92903334, 0.95708759])

In [48]:
model.fit(X, y)
y_preds = model.predict_proba(X_final)[:, 1]

In [49]:
df_preds = pd.DataFrame({
    "PatientID": df_test.PatientID,
    "subtaskID": "Task3",
    "Answer": y_preds
})

df_preds.head()

                              PatientID subtaskID  Answer
0  a00fa494-651e-4674-8fb8-aa006b14cbf7     Task3    0.69
1  f31cda69-4e3f-4265-928c-3fe9b83f0896     Task3    0.75
2  e4d181d2-803a-42f5-8065-239dd591fb9d     Task3    0.80
3  c585efb2-37e3-4620-aeda-a2299191d3a9     Task3    0.53
4  74fbfa2b-901e-4028-b325-9aaaa07cbf4d     Task3    0.86

In [50]:
submission = pd.concat([subtasks, df_preds])
submission

                                PatientID subtaskID  Answer
0    a00fa494-651e-4674-8fb8-aa006b14cbf7     Task1    0.00
1    f31cda69-4e3f-4265-928c-3fe9b83f0896     Task1    1.00
2    e4d181d2-803a-42f5-8065-239dd591fb9d     Task1    0.00
3    c585efb2-37e3-4620-aeda-a2299191d3a9     Task1    2.00
4    74fbfa2b-901e-4028-b325-9aaaa07cbf4d     Task1    0.00
..                                    ...       ...     ...
416  3fd9395f-eb15-4462-b022-d449e9e1d2d4     Task3    0.78
417  c2221f9b-fcc0-48c2-a988-90eb10a9857b     Task3    0.76
418  8818b962-4645-42f6-88c7-9a1f26fae3d8     Task3    0.68
419  4b46f134-1962-444e-ab2e-f35e24fca2b7     Task3    0.34
420  f16fc91c-ec4c-4440-b316-48d4e9084dc1     Task3    0.90

[1263 rows x 3 columns]

In [51]:
submission.to_csv("submission.csv", index=False)