In [178]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,ID,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,...,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,1,27,79,Low,High,Yes,8,63,High,Yes,...,Low,Medium,Public,Negative,5,No,College,Moderate,Female,69
1,2,16,86,High,Medium,Yes,7,94,Medium,Yes,...,Low,High,Public,Neutral,3,No,High School,Moderate,Female,69
2,3,22,87,Low,Medium,No,8,83,Low,Yes,...,Low,Medium,Public,Neutral,1,No,College,Far,Male,66
3,4,18,100,High,Medium,Yes,10,86,Medium,Yes,...,Medium,Medium,Public,Neutral,3,No,High School,Near,Male,72
4,5,35,78,High,Low,Yes,10,99,Medium,Yes,...,Low,Medium,Private,Positive,2,No,High School,Near,Male,72

In [179]:
#subtasks

def subtask2(nr):
    if nr < 7:
        return "TRUE"
    else:
        return "FALSE"

subtask_1 = abs(df_test.Hours_Studied - df_train.Hours_Studied.mean())
subtask_2 = df_test.Sleep_Hours.apply(subtask2)
subtask_3 = df_test.Previous_Scores.apply(lambda x: len(df_train[df_train.Previous_Scores >= x]))
subtask_4 = df_test.Motivation_Level.apply(lambda x: len(df_train[df_train.Motivation_Level == x]))

subtask1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.ID,
    "answer": subtask_1
})

subtask2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.ID,
    "answer": subtask_2
})

subtask3 = pd.DataFrame({
    "subtaskID": 3,
    "datapointID": df_test.ID,
    "answer": subtask_3
})

subtask4 = pd.DataFrame({
    "subtaskID": 4,
    "datapointID": df_test.ID,
    "answer": subtask_4
})

subtasks = pd.concat([subtask1, subtask2, subtask3, subtask4])

subtasks

      subtaskID  datapointID    answer
0             1         5286  0.032923
1             1         5287  2.032923
2             1         5288  1.032923
3             1         5289  7.967077
4             1         5290  1.032923
...         ...          ...       ...
1317          4         6603      2688
1318          4         6604      2688
1319          4         6605      1039
1320          4         6606      1558
1321          4         6607      2688

[5288 rows x 3 columns]

In [180]:
df_train.isna().sum()

ID                             0
Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               60
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      69
Distance_from_Home            51
Gender                         0
Exam_Score                     0
dtype: int64

In [181]:
for col in df_train.columns:
    print(f"{col} - {df_train[col].dtype}")

ID - int64
Hours_Studied - int64
Attendance - int64
Parental_Involvement - object
Access_to_Resources - object
Extracurricular_Activities - object
Sleep_Hours - int64
Previous_Scores - int64
Motivation_Level - object
Internet_Access - object
Tutoring_Sessions - int64
Family_Income - object
Teacher_Quality - object
School_Type - object
Peer_Influence - object
Physical_Activity - int64
Learning_Disabilities - object
Parental_Education_Level - object
Distance_from_Home - object
Gender - object
Exam_Score - int64

In [183]:
#preprocessing
#imputing and encoding

to_impute = {
    "Teacher_Quality": "Medium",
    "Parental_Education_Level": "High School",
    "Distance_from_Home": "Moderate"
}

for col, val in to_impute.items():
    df_train[col] = df_train[col].fillna(val)
    df_test[col] = df_test[col].fillna(val)

to_encode = ["Parental_Involvement", "Access_to_Resources", "Extracurricular_Activities", "Motivation_Level", "Internet_Access", "Family_Income", "Teacher_Quality", "School_Type", "Peer_Influence", "Learning_Disabilities", "Parental_Education_Level", "Distance_from_Home", "Gender"]

categories = [
    ["Low", "Medium", "High"],                    # Parental_Involvement
    ["Low", "Medium", "High"],                    # Access_to_Resources
    ["No", "Yes"],                                # Extracurricular_Activities
    ["Low", "Medium", "High"],                    # Motivation_Level
    ["No", "Yes"],                                # Internet_Access
    ["Low", "Medium", "High"],                    # Family_Income
    ["Low", "Medium", "High"],                    # Teacher_Quality
    ["Public", "Private"],                        # School_Type
    ["Negative", "Neutral", "Positive"],         # Peer_Influence
    ["No", "Yes"],                                # Learning_Disabilities
    ["High School", "College", "Postgraduate"],  # Parental_Education_Level
    ["Near", "Moderate", "Far"],                  # Distance_from_Home
    ["Male", "Female"]                            # Gender
]

from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder(categories=categories)

df_train[to_encode] = enc.fit_transform(df_train[to_encode])
df_test[to_encode] = enc.transform(df_test[to_encode])

df_train.head()

,ID,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,...,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,1,27,79,0.0,2.0,1.0,8,63,2.0,1.0,...,0.0,1.0,0.0,0.0,5,0.0,1.0,1.0,1.0,69
1,2,16,86,2.0,1.0,1.0,7,94,1.0,1.0,...,0.0,2.0,0.0,1.0,3,0.0,0.0,1.0,1.0,69
2,3,22,87,0.0,1.0,0.0,8,83,0.0,1.0,...,0.0,1.0,0.0,1.0,1,0.0,1.0,2.0,0.0,66
3,4,18,100,2.0,1.0,1.0,10,86,1.0,1.0,...,1.0,1.0,0.0,1.0,3,0.0,0.0,0.0,0.0,72
4,5,35,78,2.0,0.0,1.0,10,99,1.0,1.0,...,0.0,1.0,1.0,2.0,2,0.0,0.0,0.0,0.0,72

In [184]:
df_train.columns

Index(['ID', 'Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [185]:
features = ['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender']

target = "Exam_Score"

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
3210,19,96,1.0,1.0,0.0,7,57,2.0,1.0,0,0.0,1.0,0.0,2.0,3,0.0,0.0,0.0,1.0
3878,23,87,2.0,2.0,1.0,8,91,2.0,1.0,0,2.0,1.0,1.0,2.0,3,0.0,0.0,1.0,0.0
318,16,79,1.0,1.0,1.0,6,67,0.0,0.0,2,1.0,2.0,1.0,2.0,3,0.0,1.0,0.0,0.0
274,19,78,1.0,1.0,0.0,7,76,2.0,1.0,2,1.0,0.0,0.0,1.0,3,0.0,1.0,1.0,1.0
4558,12,80,1.0,1.0,1.0,7,59,2.0,1.0,1,0.0,2.0,0.0,2.0,2,0.0,0.0,0.0,1.0

In [194]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostRegressor #ts is also good
from sklearn.metrics import mean_absolute_error

model = LinearRegression().fit(X_train, y_train)
y_preds = model.predict(X_valid)
mean_absolute_error(y_valid, y_preds)

0.5075003642840337

In [187]:
y_final = model.predict(X_final)

In [188]:
df_preds = pd.DataFrame({
    "subtaskID": 5,
    "datapointID": df_test.ID,
    "answer": y_final
})

df_preds.head()

   subtaskID  datapointID     answer
0          5         5286  64.623115
1          5         5287  65.292537
2          5         5288  71.519127
3          5         5289  64.300235
4          5         5290  66.422029

In [189]:
submission = pd.concat([subtasks, df_preds])

submission

      subtaskID  datapointID     answer
0             1         5286   0.032923
1             1         5287   2.032923
2             1         5288   1.032923
3             1         5289   7.967077
4             1         5290   1.032923
...         ...          ...        ...
1317          5         6603  68.659479
1318          5         6604   72.38478
1319          5         6605  66.058293
1320          5         6606   63.41079
1321          5         6607  71.896532

[6610 rows x 3 columns]

In [190]:
submission.to_csv("submission.csv", index=False)