In [12]:
import pandas as pd
import numpy as np

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,SampleID,Text,RevisedText
0,747,She forgot her umbrella it started to rain.,"She forgot her umbrella, and then it started t..."
1,1382,He could have bought the house if he has enoug...,He could have bought the house if he had enoug...
2,241,I have a meeting with a principal of a school.,I have a meeting with the principal of the sch...
3,1647,26. You wanna grab some dinner later?,26. Do you want to have dinner later?
4,1461,The bicycle is more cheaper than the car.,The bicycle is cheaper than the car.

In [13]:
X = df_train.Text
X_final = df_test.Text

X.head()

0          She forgot her umbrella it started to rain.
1    He could have bought the house if he has enoug...
2       I have a meeting with a principal of a school.
3                26. You wanna grab some dinner later?
4            The bicycle is more cheaper than the car.
Name: Text, dtype: object

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(analyzer='char', ngram_range=((3, 5)))
X = vect.fit_transform(X)
X_final = vect.transform(X_final)

X

<1614x38697 sparse matrix of type '<class 'numpy.float64'>'
	with 217790 stored elements in Compressed Sparse Row format>

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
sims = cosine_similarity(X_final, X)
matches = np.argmax(sims, axis=1)

matches[:5]

array([1112,  465,  689,  215, 1165], dtype=int64)

In [16]:
preds = []

for idx in matches:
    good = df_train.iloc[idx]["RevisedText"]
    preds.append(good)

preds[:5]

['The cafe where I had breakfast was cozy.',
 'We were playing soccer when it started to rain.',
 'The car is parked in front of the house.',
 'The house was beautiful, but it needed a lot of work.',
 "I can't believe you're leaving so soon."]

In [17]:
submission = pd.DataFrame({
    "DatapointID": df_test.SampleID,
    "RevisedText": preds
})

submission

     DatapointID                                        RevisedText
0           1557           The cafe where I had breakfast was cozy.
1            527    We were playing soccer when it started to rain.
2            394           The car is parked in front of the house.
3           1790  The house was beautiful, but it needed a lot o...
4            434            I can't believe you're leaving so soon.
..           ...                                                ...
399         1113       This is the tallest building I've ever seen.
400          694  She loves reading books, and she reads every day.
401         1495        3. The book is on the shelf in the library.
402          922                         We walked across the park.
403          262  66. The team was excited about their victory i...

[404 rows x 2 columns]

In [18]:
df_test

     SampleID                                               Text
0        1557           He didn't eat no breakfast this morning.
1         527  29. When I was young, I used to played soccer ...
2         394           The car is parked in front of the house.
3        1790  They're house is beautiful, but it's location ...
4         434    I can't believe she ate the whole cake herself!
..        ...                                                ...
399      1113  This is the most hardest puzzle I've ever solved.
400       694            she loves reading books by jane austen.
401      1495                        The book it's on the shelf.
402       922             The dog was walked by Tim in the park.
403       262  The team is celebrating their victory in a com...

[404 rows x 2 columns]

In [19]:
submission.to_csv("submission.csv", index=False)