In [33]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,ID,Soil_Type,Region,Irrigation,pH,Moisture,Nitrogen,Phosphorus,Potassium,Organic_Matter,Electrical_Conductivity,Bulk_Density,Clay_Percent,Temperature,Rainfall_7d,Sunlight_hours,Slope,Suitability
0,1,Sandy,Hill,Sprinkler,6.501,25.144,45.528,33.742,122.187,NaN,0.472,1.697,6.190,19.980,23.595,6.439,6.823,Unfavorable
1,2,Clay,Plain,Sprinkler,6.322,22.391,119.376,62.453,218.362,2.464,1.786,1.350,41.372,25.102,5.063,10.392,1.038,Favorable
2,3,Sandy,Hill,Sprinkler,6.847,23.489,74.258,36.014,120.864,2.596,1.270,1.627,1.000,17.128,18.410,8.126,7.177,Favorable
3,4,Loam,Plain,Sprinkler,6.697,30.294,90.570,66.035,198.206,2.899,0.596,1.302,32.664,22.799,24.588,7.034,0.000,Favorable
4,5,Clay,Hill,NaN,6.740,24.471,81.934,58.793,142.101,4.334,1.289,1.402,53.710,15.147,7.216,4.151,14.352,Favorable

In [34]:
def nutrient_score(row):
    return 0.4 * row.Nitrogen + 0.3 * row.Phosphorus + 0.3 * row.Potassium

subtask1 = df_test.apply(nutrient_score, axis=1)

df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.ID,
    "answer": subtask1
})

df_1.head()

   subtaskID  datapointID    answer
0          1         2601   96.5909
1          1         2602  109.2507
2          1         2603  105.0137
3          1         2604   87.9858
4          1         2605   78.1208

In [35]:
def ph_class(val):
    if val < 6.0:
        return "Acid"
    elif val <= 7.5:
        return "Neutral"
    return "Alkaline"

subtask2 = df_test.pH.apply(ph_class)

df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.ID,
    "answer": subtask2
})

df_2.head()

   subtaskID  datapointID   answer
0          2         2601  Neutral
1          2         2602  Neutral
2          2         2603  Neutral
3          2         2604  Neutral
4          2         2605  Neutral

In [36]:
mediana = df_train.Moisture.median()

def is_moisturer(val):
    if val > mediana:
        return 1
    return 0

subtask3 = df_test.Moisture.apply(is_moisturer)

df_3 = pd.DataFrame({
    "subtaskID": 3,
    "datapointID": df_test.ID,
    "answer": subtask3
})

df_3.head()

   subtaskID  datapointID  answer
0          3         2601       1
1          3         2602       0
2          3         2603       0
3          3         2604       0
4          3         2605       1

In [37]:
value_dict = df_train.Soil_Type.value_counts()

subtask4 = df_test.Soil_Type.map(lambda x : value_dict[x])

df_4 = pd.DataFrame({
    "subtaskID": 4,
    "datapointID": df_test.ID,
    "answer": subtask4
})

df_4.head()

   subtaskID  datapointID  answer
0          4         2601     365
1          4         2602     937
2          4         2603     627
3          4         2604     671
4          4         2605     671

In [38]:
df_train.isna().sum()

ID                            0
Soil_Type                     0
Region                        0
Irrigation                 1181
pH                            0
Moisture                    170
Nitrogen                      0
Phosphorus                    0
Potassium                     0
Organic_Matter              220
Electrical_Conductivity       0
Bulk_Density                  0
Clay_Percent                  0
Temperature                   0
Rainfall_7d                   0
Sunlight_hours                0
Slope                         0
Suitability                   0
dtype: int64

In [39]:
df_train.dtypes

ID                           int64
Soil_Type                   object
Region                      object
Irrigation                  object
pH                         float64
Moisture                   float64
Nitrogen                   float64
Phosphorus                 float64
Potassium                  float64
Organic_Matter             float64
Electrical_Conductivity    float64
Bulk_Density               float64
Clay_Percent               float64
Temperature                float64
Rainfall_7d                float64
Sunlight_hours             float64
Slope                      float64
Suitability                 object
dtype: object

In [40]:
df_train.columns

Index(['ID', 'Soil_Type', 'Region', 'Irrigation', 'pH', 'Moisture', 'Nitrogen',
       'Phosphorus', 'Potassium', 'Organic_Matter', 'Electrical_Conductivity',
       'Bulk_Density', 'Clay_Percent', 'Temperature', 'Rainfall_7d',
       'Sunlight_hours', 'Slope', 'Suitability'],
      dtype='object')

In [41]:
df_train.head()

,ID,Soil_Type,Region,Irrigation,pH,Moisture,Nitrogen,Phosphorus,Potassium,Organic_Matter,Electrical_Conductivity,Bulk_Density,Clay_Percent,Temperature,Rainfall_7d,Sunlight_hours,Slope,Suitability
0,1,Sandy,Hill,Sprinkler,6.501,25.144,45.528,33.742,122.187,NaN,0.472,1.697,6.190,19.980,23.595,6.439,6.823,Unfavorable
1,2,Clay,Plain,Sprinkler,6.322,22.391,119.376,62.453,218.362,2.464,1.786,1.350,41.372,25.102,5.063,10.392,1.038,Favorable
2,3,Sandy,Hill,Sprinkler,6.847,23.489,74.258,36.014,120.864,2.596,1.270,1.627,1.000,17.128,18.410,8.126,7.177,Favorable
3,4,Loam,Plain,Sprinkler,6.697,30.294,90.570,66.035,198.206,2.899,0.596,1.302,32.664,22.799,24.588,7.034,0.000,Favorable
4,5,Clay,Hill,NaN,6.740,24.471,81.934,58.793,142.101,4.334,1.289,1.402,53.710,15.147,7.216,4.151,14.352,Favorable

In [42]:
#preprocesare simpla - imputing pt alea 3 coloane si un ordinal encoding pentru cele categorice

df_train.Soil_Type = df_train.Soil_Type.map({"Sandy": 0, "Loam": 1, "Clay": 2, "Silt": 3})
df_test.Soil_Type = df_test.Soil_Type.map({"Sandy": 0, "Loam": 1, "Clay": 2, "Silt": 3})

df_train.Region = df_train.Region.map({"Plain": 0, "Hill": 1, "Mountain": 2})
df_test.Region = df_test.Region.map({"Plain": 0, "Hill": 1, "Mountain": 2})

df_train.Irrigation = df_train.Irrigation.map({"None": 0, "Sprinkler": 1, "Drip": 2})
df_test.Irrigation = df_test.Irrigation.map({"None": 0, "Sprinkler": 1, "Drip": 2})

to_impute = ['Irrigation', 'Moisture', 'Organic_Matter']
for col in to_impute:
    df_train[col] = df_train[col].fillna(df_train[col].mean())
    df_test[col] = df_test[col].fillna(df_test[col].mean())

df_train.head()

,ID,Soil_Type,Region,Irrigation,pH,Moisture,Nitrogen,Phosphorus,Potassium,Organic_Matter,Electrical_Conductivity,Bulk_Density,Clay_Percent,Temperature,Rainfall_7d,Sunlight_hours,Slope,Suitability
0,1,0,1,1.000000,6.501,25.144,45.528,33.742,122.187,2.825001,0.472,1.697,6.190,19.980,23.595,6.439,6.823,Unfavorable
1,2,2,0,1.000000,6.322,22.391,119.376,62.453,218.362,2.464000,1.786,1.350,41.372,25.102,5.063,10.392,1.038,Favorable
2,3,0,1,1.000000,6.847,23.489,74.258,36.014,120.864,2.596000,1.270,1.627,1.000,17.128,18.410,8.126,7.177,Favorable
3,4,1,0,1.000000,6.697,30.294,90.570,66.035,198.206,2.899000,0.596,1.302,32.664,22.799,24.588,7.034,0.000,Favorable
4,5,2,1,1.365751,6.740,24.471,81.934,58.793,142.101,4.334000,1.289,1.402,53.710,15.147,7.216,4.151,14.352,Favorable

In [45]:
features = [col for col in df_test.columns if col != "ID"]
target = 'Suitability'

X = df_train[features]
y = df_train[target]
X_final = df_test[features]

X.head()

,Soil_Type,Region,Irrigation,pH,Moisture,Nitrogen,Phosphorus,Potassium,Organic_Matter,Electrical_Conductivity,Bulk_Density,Clay_Percent,Temperature,Rainfall_7d,Sunlight_hours,Slope
0,0,1,1.000000,6.501,25.144,45.528,33.742,122.187,2.825001,0.472,1.697,6.190,19.980,23.595,6.439,6.823
1,2,0,1.000000,6.322,22.391,119.376,62.453,218.362,2.464000,1.786,1.350,41.372,25.102,5.063,10.392,1.038
2,0,1,1.000000,6.847,23.489,74.258,36.014,120.864,2.596000,1.270,1.627,1.000,17.128,18.410,8.126,7.177
3,1,0,1.000000,6.697,30.294,90.570,66.035,198.206,2.899000,0.596,1.302,32.664,22.799,24.588,7.034,0.000
4,2,1,1.365751,6.740,24.471,81.934,58.793,142.101,4.334000,1.289,1.402,53.710,15.147,7.216,4.151,14.352

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model = RandomForestClassifier()

cross_val_score(model, X, y, cv=5, scoring='f1_macro').mean()

0.8580427617872186

In [54]:
model.fit(X, y)
y_preds = model.predict(X_final)

In [55]:
df_preds = pd.DataFrame({
    "subtaskID": 5,
    "datapointID": df_test.ID,
    "answer": y_preds
})

df_preds.head()

   subtaskID  datapointID       answer
0          5         2601    Favorable
1          5         2602    Favorable
2          5         2603    Favorable
3          5         2604  Unfavorable
4          5         2605    Favorable

In [56]:
submission = pd.concat([df_1, df_2, df_3, df_4, df_preds])
submission

      subtaskID  datapointID       answer
0             1         2601      96.5909
1             1         2602     109.2507
2             1         2603     105.0137
3             1         2604      87.9858
4             1         2605      78.1208
...         ...          ...          ...
1195          5         3796  Unfavorable
1196          5         3797    Favorable
1197          5         3798    Favorable
1198          5         3799    Favorable
1199          5         3800    Favorable

[6000 rows x 3 columns]

In [57]:
submission.to_csv("submission.csv", index=False)