In [39]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,5531,86,0,2,1,28.155961,0,18.629164,6.535593,1.316452,...,5.566873,0,0,0.232938,0,0,0,0,1,0
1,6092,62,1,0,3,28.189210,1,7.763349,1.913491,6.023577,...,9.307896,0,0,0.442326,0,0,0,0,0,0
2,5571,75,0,0,0,25.391526,0,8.449637,9.549369,1.774418,...,4.001694,0,0,4.918146,0,0,0,0,0,1
3,5608,89,0,0,0,23.581751,0,1.939227,1.322465,8.758693,...,9.700073,1,0,5.157190,0,1,0,0,1,0
4,5344,76,1,0,2,38.768590,1,9.013919,8.296794,7.892595,...,8.626984,0,0,9.413984,0,0,0,0,1,0

In [40]:
#datasetu asta e strict numeric si nici nare nicio valoare lips
#si nici nu prea sunt skewed datele

In [41]:
#subtasks
subtask1 = []

for age in df_test.Age:
    subtask1.append(len(df_train[df_train.Age == age]))

subtask2 = []

for age in df_test.Age:
    nr1 = len(df_train[(df_train.Age == age) & (df_train.Smoking == 1)])
    nr2 = len(df_train[df_train.Age == age])
    subtask2.append(nr1/nr2*100)

df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.PatientID,
    "answer": subtask1
})

df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.PatientID,
    "answer": subtask2
})

subtasks = pd.concat([df_1, df_2])
subtasks

     subtaskID  datapointID     answer
0            1         5202  44.000000
1            1         6831  66.000000
2            1         6407  50.000000
3            1         5821  64.000000
4            1         5581  56.000000
..         ...          ...        ...
425          2         6548  33.333333
426          2         6175  25.000000
427          2         4859  32.142857
428          2         6567  24.000000
429          2         4913  20.408163

[860 rows x 3 columns]

In [42]:
df_train.columns

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality',
       'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease',
       'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP',
       'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
       'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks',
       'Forgetfulness', 'Diagnosis'],
      dtype='object')

In [43]:
features = ['Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease',
        'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
        'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
        'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks','Forgetfulness']
target = 'Diagnosis'

X = df_train[features]
y = df_train[target]
X_final = df_test[features]

X.head()

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,MMSE,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness
0,86,0,2,1,28.155961,0,18.629164,6.535593,1.316452,9.620590,...,20.610337,5.566873,0,0,0.232938,0,0,0,0,1
1,62,1,0,3,28.189210,1,7.763349,1.913491,6.023577,5.039160,...,8.973483,9.307896,0,0,0.442326,0,0,0,0,0
2,75,0,0,0,25.391526,0,8.449637,9.549369,1.774418,7.951681,...,11.968872,4.001694,0,0,4.918146,0,0,0,0,0
3,89,0,0,0,23.581751,0,1.939227,1.322465,8.758693,9.262999,...,27.648573,9.700073,1,0,5.157190,0,1,0,0,1
4,76,1,0,2,38.768590,1,9.013919,8.296794,7.892595,5.928934,...,25.410148,8.626984,0,0,9.413984,0,0,0,0,1

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model = RandomForestClassifier(random_state=42)

cross_val_score(model, X, y, cv=5, scoring='roc_auc')

array([0.95847385, 0.9342047 , 0.96444395, 0.94027839, 0.96299605])

In [45]:
model.fit(X, y) #prezicem proba pt ca e cu roc auc
y_preds = model.predict_proba(X_final)
y_preds[:10]

array([[0.21, 0.79],
       [0.87, 0.13],
       [0.32, 0.68],
       [0.53, 0.47],
       [0.15, 0.85],
       [0.93, 0.07],
       [0.37, 0.63],
       [0.96, 0.04],
       [0.61, 0.39],
       [0.18, 0.82]])

In [49]:
df_preds = pd.DataFrame({
    "subtaskID": 3,
    "datapointID": df_test.PatientID,
    "answer": y_preds[:, 1]
})

df_preds.head()

   subtaskID  datapointID  answer
0          3         5202    0.79
1          3         6831    0.13
2          3         6407    0.68
3          3         5821    0.47
4          3         5581    0.85

In [50]:
submission = pd.concat([subtasks, df_preds])

submission

     subtaskID  datapointID  answer
0            1         5202   44.00
1            1         6831   66.00
2            1         6407   50.00
3            1         5821   64.00
4            1         5581   56.00
..         ...          ...     ...
425          3         6548    0.08
426          3         6175    0.24
427          3         4859    0.72
428          3         6567    0.25
429          3         4913    0.19

[1290 rows x 3 columns]

In [51]:
submission.to_csv("submission.csv", index=False)