In [10]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_test.head()

   SampleID  temperature_c
0         1         -18.11
1         2          18.18
2         3          -1.14
3         4          10.51
4         5          34.45

In [11]:
f_values = df_test.temperature_c * 9/5 + 32
f_values[:5]

0    -0.598
1    64.724
2    29.948
3    50.918
4    94.010
Name: temperature_c, dtype: float64

In [13]:
submission = pd.DataFrame({
    "SampleID": df_test.SampleID,
    "temperature_f": f_values
})

submission.head()

   SampleID  temperature_f
0         1         -0.598
1         2         64.724
2         3         29.948
3         4         50.918
4         5         94.010

In [14]:
submission.to_csv("submission.csv", index=False)