In [9]:
from collections import deque

stanga, insula, dreapta = 0, 1, 2

def is_safe(r, a):
    return r == 0 or r >= a

def valid_state(state, n):
    (rl, al, ri, ai, rr, ar, boat) = state

    if rl + ri + rr != n or al + ai + ar != n: # sa fie nru bun gen
        return False

    return (is_safe(rl, al) and is_safe(ri, ai) and is_safe(rr, ar)) #sa respecte toate regula

valid_state((1, 1, 1, 1, 1, 1, stanga), 3) #asta trb sa fie True

True

In [10]:
def bfs(n):
    start = (n, n, 0, 0, 0, 0, stanga)
    target = (0, 0, 0, 0, n, n, dreapta)

    q = deque([(start, 0)])
    visited = {start}
    moves = [(1,0), (0,1), (1,1), (2,0), (0,2)] # combinaytiile
    
    while q:
        (rl, al, ri, ai, rr, ar, boat), dist = q.popleft()
        if (rl, al, ri, ai, rr, ar, boat) == target:
            return dist

        if boat == stanga:
            # poate merge doar pe insula
            for r,a in moves:
                if rl >= r and al >= a:
                    new_state = (rl-r, al-a, ri+r, ai+a, rr, ar, insula)
                    if new_state not in visited and valid_state(new_state, n):
                        visited.add(new_state)
                        q.append((new_state, dist+1))

        elif boat == insula:
            # poate merge ori dreapta ori stanga
            for r,a in moves:
                # spre dreapta
                if ri >= r and ai >= a:
                    new_state = (rl, al, ri-r, ai-a, rr+r, ar+a, dreapta)
                    if new_state not in visited and valid_state(new_state, n):
                        visited.add(new_state)
                        q.append((new_state, dist+1))

                # înapoi spre stânga
                if ri >= r and ai >= a:
                    new_state = (rl+r, al+a, ri-r, ai-a, rr, ar, stanga)
                    if new_state not in visited and valid_state(new_state, n):
                        visited.add(new_state)
                        q.append((new_state, dist+1))

        elif boat == dreapta:
            # trebuie sa mearga inapoi pe insula
            for r,a in moves:
                if rr >= r and ar >= a:
                    new_state = (rl, al, ri+r, ai+a, rr-r, ar-a, insula)
                    if new_state not in visited and valid_state(new_state, n):
                        visited.add(new_state)
                        q.append((new_state, dist+1))

    return None

bfs(3) #asta trb sa dea 18

18

In [11]:
import pandas as pd

#subtask1
df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": [3],
    "answer": bfs(3)
})

df_1

   subtaskID  datapointID  answer
0          1            3      18

In [14]:
#subtask2

df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": range(4, 9),
    "answer": [bfs(i) for i in range(4, 9)]
})

df_2

   subtaskID  datapointID  answer
0          2            4      26
1          2            5      34
2          2            6      42
3          2            7      50
4          2            8      58

In [15]:
submission = pd.concat([df_1, df_2])
submission

   subtaskID  datapointID  answer
0          1            3      18
0          2            4      26
1          2            5      34
2          2            6      42
3          2            7      50
4          2            8      58

In [16]:
submission.to_csv("submission.csv", index=False)