In [208]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,ID,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,Footage_to_Lot_Ratio,Total_Rooms,Age_of_House,Garage_to_Footage_Ratio,Avg_Room_Size,Price,House_Orientation_Angle,Street_Alignment_Offset,Solar_Exposure_Index,Magnetic_Field_Strength,Vibration_Level
0,1,2028,2,3,1967,1.784790,2,2,1136.268444,5,58,0.000986,405.600000,11184.929934,16.722149,298.409571,235.502857,227.621575,129.770822
1,2,3519,5,3,1966,4.009947,0,10,877.567605,8,59,0.000000,439.875000,13941.315383,340.115663,43.878994,300.292055,46.684432,211.676987
2,3,4507,2,3,2014,4.122337,0,7,1093.311933,5,11,0.000000,901.400000,19686.885572,219.823215,24.542031,186.851621,10.837394,316.769266
3,4,3371,4,2,2000,1.580318,0,1,2133.114532,6,25,0.000000,561.833333,20964.530841,10.361763,147.970249,107.843644,175.620355,244.463978
4,5,2871,5,1,1974,3.426914,2,6,837.780090,6,51,0.000697,478.500000,12180.466278,329.344524,46.114469,357.571806,335.719756,135.850744

In [209]:
subtask_1 = df_test.Square_Footage + df_test.Garage_Size + df_test.Lot_Size
df_test["Total_Surface"] = subtask_1
df_train["Total_Surface"] = df_train.Square_Footage + df_train.Garage_Size + df_train.Lot_Size

subtask_2 = df_test.Garage_Size / df_test.Total_Rooms
df_test["Garage_to_Room_Ratio"] = subtask_2
df_train["Garage_to_Room_Ratio"] = df_train.Garage_Size / df_train.Total_Rooms

subtask_3 = (df_test.Solar_Exposure_Index - df_test.Vibration_Level) / df_test.Magnetic_Field_Strength
df_test["Environmental_Stability_Index"] = subtask_3
df_train["Environmental_Stability_Index"] = (df_train.Solar_Exposure_Index - df_train.Vibration_Level) / df_train.Magnetic_Field_Strength

subtask_4 = abs(df_test.Square_Footage - df_train.Square_Footage.mean())

subtask1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.ID,
    "answer": subtask_1
})

subtask2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.ID,
    "answer": subtask_2
})

subtask3 = pd.DataFrame({
    "subtaskID": 3,
    "datapointID": df_test.ID,
    "answer": subtask_3
})

subtask4 = pd.DataFrame({
    "subtaskID": 4,
    "datapointID": df_test.ID,
    "answer": subtask_4
})

subtasks = pd.concat([subtask1, subtask2, subtask3, subtask4])

subtasks

     subtaskID  datapointID       answer
0            1          801  4015.098092
1            1          802  2312.369622
2            1          803  4710.792970
3            1          804  4937.479598
4            1          805  3649.980987
..         ...          ...          ...
195          4          996   953.100000
196          4          997  2197.900000
197          4          998  1677.100000
198          4          999   955.900000
199          4         1000   381.100000

[800 rows x 3 columns]

In [210]:
df_train.columns

Index(['ID', 'Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality',
       'Footage_to_Lot_Ratio', 'Total_Rooms', 'Age_of_House',
       'Garage_to_Footage_Ratio', 'Avg_Room_Size', 'Price',
       'House_Orientation_Angle', 'Street_Alignment_Offset',
       'Solar_Exposure_Index', 'Magnetic_Field_Strength', 'Vibration_Level',
       'Total_Surface', 'Garage_to_Room_Ratio',
       'Environmental_Stability_Index'],
      dtype='object')

In [211]:
features = ['Total_Surface', 'Environmental_Stability_Index', 'Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built', 'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'Footage_to_Lot_Ratio', 'Total_Rooms', 'Age_of_House',
       'Garage_to_Footage_Ratio', 'Avg_Room_Size', 'House_Orientation_Angle', 'Street_Alignment_Offset', 'Solar_Exposure_Index', 'Magnetic_Field_Strength', 'Vibration_Level', 'Garage_to_Room_Ratio']

target = 'Price'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

X.head()

,Total_Surface,Environmental_Stability_Index,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,Footage_to_Lot_Ratio,Total_Rooms,Age_of_House,Garage_to_Footage_Ratio,Avg_Room_Size,House_Orientation_Angle,Street_Alignment_Offset,Solar_Exposure_Index,Magnetic_Field_Strength,Vibration_Level,Garage_to_Room_Ratio
0,-0.627625,0.039647,-0.627722,-0.681986,1.261133,-0.957011,-0.770120,1.201331,-1.234358,-0.200274,0.035928,0.957011,0.888803,-0.581257,-1.534059,1.077829,0.507474,0.508445,-0.445273,0.790784
1,0.563273,0.229716,0.563185,1.429971,1.261133,-1.005096,0.965113,-1.237920,1.511520,-0.407560,1.832335,1.005096,-0.842330,-0.503911,1.536054,-1.345349,1.129535,-1.243341,0.349983,-1.039271
2,1.352383,-1.611240,1.352331,-0.681986,1.261133,1.302982,1.052757,-1.237920,0.481816,-0.234693,0.035928,-1.302982,-0.842330,0.537573,0.394066,-1.529440,0.040357,-1.590403,1.370362,-1.039271
3,0.443140,-0.125070,0.444973,0.725985,0.035244,0.629793,-0.929572,-1.237920,-1.577593,0.598458,0.634731,-0.629793,-0.842330,-0.228698,-1.594441,-0.354381,-0.718223,0.004983,0.668324,-1.039271
4,0.046910,0.065622,0.045608,1.429971,-1.190644,-0.620416,0.510449,1.201331,0.138581,-0.439440,0.634731,0.620416,0.380498,-0.416749,1.433799,-1.324067,1.679497,1.555023,-0.386241,0.485775

In [212]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

model = Ridge().fit(X, y)
y_preds = model.predict(X_valid)
mean_absolute_error(y_valid, y_preds)

249.46540826823994

In [213]:
y_final = model.predict(X_final)

In [214]:
df_preds = pd.DataFrame({
    "subtaskID": 5,
    "datapointID": df_test.ID,
    "answer": y_final
})

df_preds.head()

   subtaskID  datapointID        answer
0          5          801  22350.666658
1          5          802  15383.235942
2          5          803  26173.458041
3          5          804  19835.941338
4          5          805  16142.012882

In [215]:
submission = pd.concat([subtasks, df_preds])

submission

     subtaskID  datapointID        answer
0            1          801   4015.098092
1            1          802   2312.369622
2            1          803   4710.792970
3            1          804   4937.479598
4            1          805   3649.980987
..         ...          ...           ...
195          5          996  23037.567227
196          5          997   2049.460585
197          5          998  19838.686692
198          5          999   8290.686161
199          5         1000  13285.365952

[1000 rows x 3 columns]

In [216]:
submission.to_csv("submission.csv", index=False)