In [27]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,datapointID,X,Y,Z,Class
0,11.-92734-7-5153-9845.59462205.50379-.062544069,NaN,NaN,NaN,NaN
1,2133109-8-.23252-,NaN,NaN,NaN,NaN
2,3-39.690811899155420-1565043411407,NaN,NaN,NaN,NaN
3,4,-0.875838,-0.133781,-0.254318,0.0
4,5,0.476464,0.567121,-0.587028,0.0

In [28]:
df_train = df_train[(df_train.Class == 0) | (df_train.Class == 1)]

df_train.head()

   datapointID         X         Y         Z  Class
3            4 -0.875838 -0.133781 -0.254318    0.0
4            5  0.476464  0.567121 -0.587028    0.0
9           10 -0.672903 -0.832620 -0.806907    0.0
21          22 -0.179485  0.434237 -0.540987    0.0
29          30  0.732729  0.165628  0.489996    1.0

In [35]:
df_train.columns

Index(['datapointID', 'X', 'Y', 'Z', 'Class'], dtype='object')

In [36]:
features = ['X', 'Y', 'Z']
target = 'Class'

X = df_train[features]
y = df_train[target]
X_final = df_test[features]

X.head()

           X         Y         Z
3  -0.875838 -0.133781 -0.254318
4   0.476464  0.567121 -0.587028
9  -0.672903 -0.832620 -0.806907
21 -0.179485  0.434237 -0.540987
29  0.732729  0.165628  0.489996

In [57]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model = SVC(kernel='rbf', gamma=10, C=18)

cross_val_score(model, X, y, cv=5, scoring='f1_macro').mean()

0.8818671517735506

In [58]:
model.fit(X, y)
y_preds = model.predict(X_final)

In [63]:
df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_train.datapointID,
    "answer": df_train.Class
})

df_1.head()

    subtaskID datapointID  answer
3           1           4     0.0
4           1           5     0.0
9           1          10     0.0
21          1          22     0.0
29          1          30     1.0

In [64]:
df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.datapointID,
    "answer": y_preds
})

df_2.head()

   subtaskID  datapointID  answer
0          2            0     0.0
1          2            1     0.0
2          2            2     0.0
3          2            3     1.0
4          2            4     0.0

In [65]:
submission = pd.concat([df_1, df_2])
submission.answer = submission.answer.astype("int64")
submission.datapointID = submission.datapointID.astype("float64")
submission

       subtaskID  datapointID  answer
3              1          4.0       0
4              1          5.0       0
9              1         10.0       0
21             1         22.0       0
29             1         30.0       1
...          ...          ...     ...
19131          2      19131.0       0
19132          2      19132.0       0
19133          2      19133.0       0
19134          2      19134.0       1
19135          2      19135.0       0

[20416 rows x 3 columns]

In [66]:
submission.to_csv("submission.csv", index=False)